Document: zxcvbn-c
Title: Debian zxcvbn-c Manual
Author: <insert document author here>
Abstract: This manual describes what zxcvbn-c is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zxcvbn-c/zxcvbn-c.sgml.gz

Format: postscript
Files: /usr/share/doc/zxcvbn-c/zxcvbn-c.ps.gz

Format: text
Files: /usr/share/doc/zxcvbn-c/zxcvbn-c.text.gz

Format: HTML
Index: /usr/share/doc/zxcvbn-c/html/index.html
Files: /usr/share/doc/zxcvbn-c/html/*.html
